#!/usr/bin/env python3
"""
.. module:: kirk
    :platform: Linux
    :synopsis: script to run the main entry point
.. moduleauthor:: Andrea Cervesato <andrea.cervesato@suse.com>
"""

# pylint: disable=invalid-name
import os
import sys

# include tool library
sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))

if __name__ == "__main__":
    import libkirk.main
    libkirk.main.run()
