#!/usr/bin/env python3
"""
.. module:: runkirk
    :platform: Linux
    :synopsis: helper script to run tool
.. moduleauthor:: Andrea Cervesato <andrea.cervesato@suse.com>
"""

# pylint: disable=invalid-name
import os
import sys

# include tool library
sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))

if __name__ == "__main__":
    import kirk.main
    kirk.main.run()
