# Copyright (c) 2022 Andrea Cervesato <andrea.cervesato@suse.com>

name: "Static analysis"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: python:3.9-alpine

    steps:
    - name: Show OS
      run: cat /etc/os-release

    - name: Install system dependencies
      run: apk add --no-cache git gcc musl-dev

    - name: Git checkout
      uses: actions/checkout@v7

    - name: Install dependencies
      run: pip install .[testing,ssh,ltx] ruff pyrefly

    - name: Test kirk
      run: ./kirk --help

    - name: Static formatting
      run: ruff format --check

    - name: Static linting
      run: ruff check

    - name: Static type checking
      run: pyrefly check libkirk
