# Copyright (c) 2025 Andrea Cervesato <andrea.cervesato@suse.com>

name: "Test LTX"
on: [push, pull_request]

jobs:
  python3:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        python-version: [
          "3.7",
          "3.8",
          "3.9",
          "3.10",
          "3.11",
          "3.12",
          "3.13",
          "3.14"
        ]

    container:
      image: python:${{ matrix.python-version }}-alpine

    steps:
    - name: Show OS
      run: cat /etc/os-release

    - name: Install system dependencies
      run: apk add --no-cache git make gcc musl-dev linux-headers

    - name: Git checkout
      uses: actions/checkout@v7

    - name: Install dependencies
      run: pip install .[testing,ltx]

    - name: Checkout ltx
      uses: actions/checkout@v7
      with:
        repository: linux-test-project/ltx
        path: ltx

    - name: Compile ltx
      run: make -C ltx

    - name: Test with pytest
      env:
        TEST_LTX_BINARY: ./ltx/ltx
      run: python3 -m pytest -m "ltx"
